.build_template: &build_template
  stage: build
  tags:
    - build
  image: ${IMAGE}
  variables:
    # Enable ccache for all build jobs. See configure_ci_environment.sh for more ccache related settings.
    IDF_CCACHE_ENABLE: "1"
    BATCH_BUILD: "1"
    V: "0"
    WARNING_STR: ""


.build_sdk: &build_sdk |
  if [ "${SDKCONFIG_DEFAULTS}" ]; then
    idf.py -DSDKCONFIG_DEFAULTS="${SDKCONFIG_DEFAULTS}" set-target ${IDF_TARGET}
  else
    idf.py set-target ${IDF_TARGET}
  fi

  idf.py build

.build_examples_template: &build_examples_template
  <<: *build_template
  artifacts:
    when: always
    paths:
      - "**/build*/size.json"
      - "**/build*/build_log.txt"
      - "**/build*/*.bin"
      # upload to s3 server to save the artifacts size
      - "**/build*/*.map"
      - "**/build*/*.elf"
      - "**/build*/flasher_args.json"
      - "**/build*/flash_project_args"
      - "**/build*/config/sdkconfig.json"
      - "**/build*/bootloader/*.bin"
      - "**/build*/bootloader/*.elf"
      - "**/build*/partition_table/*.bin"
      - size_info.txt
    expire_in: 1 week
  variables:
    IDF_CI_BUILD: "1"
  script:
    - *build_sdk

build_platform_esp32s3_box:
  extends:
    - .build_examples_template
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v5.0
      - IMAGE: espressif/idf:release-v5.1
      - IMAGE: espressif/idf:release-v5.2
      - IMAGE: espressif/idf:latest # v5.3
  variables:
    IDF_TARGET: esp32s3
    SDKCONFIG_DEFAULTS: sdkconfig.defaults;sdkconfig.esp-box

build_platform_esp32s3_devkitc:
  extends:
    - .build_examples_template
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v5.0
      - IMAGE: espressif/idf:release-v5.1
      - IMAGE: espressif/idf:release-v5.2
      - IMAGE: espressif/idf:latest # v5.3
  variables:
    IDF_TARGET: esp32s3

build_platform_esp32c6_devkitc:
  extends:
    - .build_examples_template
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v5.1
      - IMAGE: espressif/idf:release-v5.2
      - IMAGE: espressif/idf:latest # v5.3
  variables:
    IDF_TARGET: esp32c6
